---
- name: Exercise 3c
  hosts: localhost
  gather_facts: True
  tasks:
    - ansible.builtin.debug:
        var: ansible_host
- name: Exercise3c - Another Play
  hosts: cisco
  gather_facts: True 
  tasks:
    - ansible.builtin.debug:
        var: ansible_connection
    - ansible.builtin.debug:
        var: ansible_host

