---
- name: Exercise5a
  hosts: juniper
  gather_facts: False

  tasks:
  - junipernetworks.junos.junos_command:
     commands: show interfaces terse
    register: interfaces
  

  - ansible.builtin.debug:
       msg: "IP is {{ interfaces['stdout_lines'][0][21].split()[-1] }}"

#  - ansible.builtin.debug:
 #      msg: "IP is {{ ip }}"
