---
- name: Exercise1a
  hosts: arista5
  gather_facts: True
  gather_subset: all

  tasks:
    - name: Print arista5 ansible_facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print arista5 all ipv4 address
      ansible.builtin.debug:
        var: ansible_facts.net_all_ipv4_addresses

    - name: Print arista2 ansibel network os
      ansible.builtin.debug:
        var: ansible_network_os

    - name: Print arista5 ansible host
      ansible.builtin.debug:
        var: ansible_host

    - name: Print arista5 desired OS version
      ansible.builtin.debug:
        var: desired_eos_version
      
