---
- name: Configure loging banner
  hosts: cisco
  gather_facts: False
  tasks:
     - name: COnfigure login banner
       cisco.ios.ios_banner:
         banner: login
         text:  |
          **********************************************************
          This is a test login banner for class4, exercise4.

          Configured via Ansible
          **********************************************************
         state: present
       notify: write mem

  handlers:
     - name: write mem
       cisco.ios.ios_command:
         commands: write mem
       #changed_when: True
