---
- name: Exercise4
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Generate interface config
      ansible.builtin.template:
        src: interfaces.j2
        dest: "./CFGS/{{ inventory_hostname }}/01-{{ inventory_hostname }}-intf.txt"

    - name: Generat bgp config
      ansible.builtin.template:
        src: bgp.j2
        dest: "./CFGS/{{ inventory_hostname }}/02-{{ inventory_hostname }}-bgp.txt"

    - name: concatenate both files
      ansible.builtin.assemble:
        src: "./CFGS/{{ inventory_hostname }}/"
        dest: "./CFGS/{{ inventory_hostname }}-config.txt"
    
    - name: Deploy config
      cisco.nxos.nxos_config:
        src: "./CFGS/{{ inventory_hostname }}-config.txt"


    - name: Verify BGP
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: output
      tags: bgp_out

    - name: print output
      ansible.builtin.debug:
        var: output.stdout_lines[0]
      tags: bgp_out
