---
- name: Exercise3a
  hosts: nxos
  gather_facts: false
  vars:
    fsm_template: "cisco_nxos_show_ip_bgp_summary.textfsm"

  tasks:
    - name: CLI output
      cisco.nxos.nxos_command:
        commands: show ip bgp summary
      register: output	  
    
    - name: no stdout
      ansible.builtin.debug:
        var: output
    

    - name: Print no parsin
      ansible.builtin.debug:
        var: output.stdout[0]

    - name: stdout lines
      ansible.builtin.debug:
        var: output.stdout_lines[0]

    - name: stdout lines no zero
      ansible.builtin.debug:
        var: output.stdout_lines


    - name: parse
      ansible.builtin.set_fact:
        show_bgp: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - name: Print
      ansible.builtin.debug:
        msg: "{{ show_bgp[0] }}"
      when: show_bgp != []

 
    - name: Chekc if BGP is UP
      ansible.builtin.assert:
        that: 
          - "'shut' not in show_bgp[0]['STATE_PFXRCD']"
          - "'Idle' not in show_bgp[0]['STATE_PFXRCD']"
          - show_bgp[0]['STATE_PFXRCD'] | int >= 2
      when: show_bgp != []
