---
- name: Exercise4
  hosts: arista
  gather_facts: False

  tasks:
    - name: Create VLAN_id
      arista.eos.eos_vlans:
        config:
          - name: "{{ vlan_name }}"
            vlan_id: "{{ vlan_id }}"
        state: merged

    - name: "Assign {{ intf_name }} to VLAN {{ vlan_id }}"
      arista.eos.eos_l2_interfaces:
        config:
          - name: "{{ intf_name }}"
            access:
              vlan: "{{ vlan_id }}"
        state: merged

    - name: Check show vlan on Arista
      arista.eos.eos_command:
        commands: show vlan | json
      register: output


    - name: parse data
      ansible.builtin.set_fact:
        interfaces_dict: '{{ output.stdout[0].vlans[vlan_id].interfaces }}'
        vlan_status: '{{ output.stdout[0].vlans[vlan_id].status }}'


    - name: Check VLAN is applied to right interface
      ansible.builtin.assert:
        that:
          - vlan_status == 'active'
          - "'Ethernet7' in interfaces_dict"

    

