---
- name: Exercise2
  hosts: arista
  gather_facts: false
  
  vars:
    ansible_user: pyclass
    ansible_ssh_pass: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
 
  tasks:
    - name: EOS usng env variable
      arista.eos.eos_command:
        commands: show vlan
      register: output
   
    - name: Show output
      ansible.builtin.debug:
        var: output.stdout_lines[0]
     
