---
- name: Exercise 5b
  hosts: arista
  gather_facts: False

  tasks:
    - name: CLI
      arista.eos.eos_command:
        commands: show version
      register: output

    - name: Removw wrapper
      ansible.builtin.set_fact:
        output: "{{ output.stdout[0] }}"

    - name: Print raw
      ansible.builtin.debug:
        msg: "{{ output }}"

    - name: Display as a string
      ansible.builtin.debug:
        msg: "{{ output.splitlines() }}"

    - name: APply regex for parsing
      ansible.builtin.set_fact:
        os_list: "{{ output |  regex_search('^Software image version: (\\S+).*$', '\\1', multiline=True) }}"
      
    - name: Print os_list
      ansible.builtin.debug:
        msg: "{{ os_list }}"

    - name: Print and filter
      ansible.builtin.debug:
        msg:
         - "-----------------------"
         - "{{ inventory_hostname }}:"
         - "{{ os_list[0] }}"
         - "-----------------------"
     
